name: Unzip File

on:
  workflow_dispatch:

jobs:
  unzip_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Unzip file
      run: Apk.zip -d extracted-folder
