name: Unzip APK File

on:
  workflow_dispatch:

jobs:
  unzip_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files (debug)
      run: ls -l

    - name: Unzip APK file
      run: unzip Apk.zip -d extracted-folder
