name: Android CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.gitignore'

env:
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Unzip Apk.zip to extracted-folder
        run: unzip Apk.zip -d extracted-folder

      - name: 🔁 Git Commit & Push Extracted Code
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add extracted-folder/
          git commit -m "🗂️ Extracted Apk.zip to extracted-folder [auto]" || echo "No changes to commit"
          git push origin main

      - name: 🛠 Make gradlew Executable
        run: chmod +x extracted-folder/NewProject10/gradlew

      - name: ⚙️ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: 📱 Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'

      - name: 📜 Accept Licenses
        run: yes | sdkmanager --licenses

      - name: 🧹 Clean Project
        run: ./gradlew clean --no-daemon
        working-directory: extracted-folder/NewProject10

      - name: 🔨 Build Debug APK
        run: |
          echo "🚀 Building Debug APK..."
          ./gradlew assembleDebug --no-daemon --stacktrace 2>&1 | tee build.log
        working-directory: extracted-folder/NewProject10
        continue-on-error: true

      - name: 🔨 Build Release APK
        run: |
          echo "🚀 Building Release APK..."
          ./gradlew assembleRelease --no-daemon --stacktrace 2>&1 | tee -a build.log
        working-directory: extracted-folder/NewProject10
        continue-on-error: true

      - name: 🔍 Extract and Show Critical Errors
        if: always()
        run: |
          echo "📋 CRITICAL BUILD ERRORS:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          grep -E 'e: .*\.kt:[0-9]+:[0-9]+:' extracted-folder/NewProject10/build.log | head -n 15 >> $GITHUB_STEP_SUMMARY || true
          grep -E -i '(FAILED|Exception|Error|unresolved|duplicate class|missing)' extracted-folder/NewProject10/build.log | grep -v -E '(Download|> Task)' | head -n 10 >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "🚨 ERRORS FOUND:"
          grep -E -i '(error|failed|exception|unresolved|duplicate|e: .*\.kt)' extracted-folder/NewProject10/build.log | head -n 20 || echo "No errors detected"

      - name: 📦 Check APK Build Status
        if: always()
        run: |
          DEBUG_APK="extracted-folder/NewProject10/app/build/outputs/apk/debug/app-debug.apk"
          RELEASE_APK="extracted-folder/NewProject10/app/build/outputs/apk/release/app-release-unsigned.apk"

          echo "### 📦 APK Build Results" >> $GITHUB_STEP_SUMMARY

          if [ -f "$DEBUG_APK" ]; then
            echo "✅ Debug APK built successfully!"
            echo "- ✅ Debug APK: Built" >> $GITHUB_STEP_SUMMARY
            ls -lh "$DEBUG_APK"
          else
            echo "❌ Debug APK build failed"
            echo "- ❌ Debug APK: Failed" >> $GITHUB_STEP_SUMMARY
          fi

          if [ -f "$RELEASE_APK" ]; then
            echo "✅ Release APK built successfully!"
            echo "- ✅ Release APK: Built" >> $GITHUB_STEP_SUMMARY
            ls -lh "$RELEASE_APK"
          else
            echo "❌ Release APK build failed"
            echo "- ❌ Release APK: Failed" >> $GITHUB_STEP_SUMMARY
          fi

      - name: 📤 Upload APK Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            extracted-folder/NewProject10/app/build/outputs/apk/debug/*.apk
            extracted-folder/NewProject10/app/build/outputs/apk/release/*.apk
          if-no-files-found: warn

      - name: ❌ Final Error Check
        if: always()
        run: |
          if grep -q -i -E '(FAILED|error|exception|unresolved)' extracted-folder/NewProject10/build.log; then
            echo "💥 Build failed with errors - check the error summary above"
            exit 1
          else
            echo "✅ Build completed successfully"
          fi
